### ISSUE TITLE
Can you have pretty search results and "view page source" ?

### ISSUE THREAD

**Issue by JonHertzig** [TimKam/sphinx-pretty-searchresults#12]
The sphinx-pretty-searchresults plugin works great except that the "View page source" link now shows something that doesn't look like the source (I assume it looks like the text files that the search is using instead).   Is there a way to have both ?

**Comment by TimKam** [comment]
Thanks for pointing this out. By default, you can't have both. It shouldn't be too hard to support it, though.

Right now, the extension is overwriting the source files that are copied to the build directory.
Instead, the extension could copy the prettified source files to its own directory and adjust the link in the search script (or rename the sources folder and adjust the sources link, whatever is less invasive).

I'm not sure yet how much JavaScript customization this needs, but I'll look into it.

**Comment by JonHertzig** [comment]
Thanks Tim, at the moment it's a bit of a dealbreaker for us -- for an
otherwise great plugin. Will anxiously await new developments... :)

**Comment by TimKam** [comment]
The solution should be https://github.com/TimKam/sphinx-pretty-searchresults/releases/tag/v0.3.0.
Please confirm.

**Comment by JonHertzig** [comment]
Thanks so much for the fast solution -- waiting for our systems people to install here, so I can test (might be a couple of days).

**Comment by JonHertzig** [comment]
having issues -- using a variation of the read_the_docs theme, which includes these lines in https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/breadcrumbs.html :

```
          {% elif show_source and source_url_prefix %}
            <a href="{{ source_url_prefix }}{{ pagename }}{{ suffix }}">{{ _('View page source') }}</a>
          {% elif show_source and has_source and sourcename %}
            <a href="{{ pathto('_sources/' + sourcename, true)|e }}" rel="nofollow"> {{ _('View page source') }}</a>
```

**Comment by JonHertzig** [comment]
(right now it's still picking up the prettysearchresults source instead of the rst source when you click "View page source")

**Comment by TimKam** [comment]
The problem is that the template is no longer loading the source link as a separate HTML snippet.
Are you or your devs in control of the template you are using?
Then change this:
`<a href="{{ pathto('_sources/' + sourcename, true)|e }}" rel="nofollow"> {{ _('View page source') }}</a>`
to:
`<a href="{{ pathto('_raw_sources/' + sourcename, true)|e }}" rel="nofollow"> {{ _('View page source') }}</a>`
Please let me know if this is a practicable solution for you.

**Comment by JonHertzig** [comment]
Cheers, works beautifully.

**Comment by TimKam** [comment]
Great, I adjusted the README accordingly.
