### ISSUE TITLE
Maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by benjamin-rose** [TimKam/sphinx-pretty-searchresults#17]
I installed sphinx-pretty-searchresults and added it to my conf.py as an extension. Now whenever I build my project, I get a recursion error. 

> Recursion error:
> maximum recursion depth exceeded in cmp
> This can happen with very large or deeply nested files. You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
> import sys; sys.setrecursionlimit(1500)

I don't have very large files (the largest is just a few KB and even my images are only a few hundred KB) nor are they deeply nested (when I run 'make' all my .rst files are in a single directory).

I increased the recursion limit up to 2500 with no luck. Removing sphinx-pretty-searchresults from conf.py makes the recursion error immediately go away.

I'm using Sphinx v1.5.5.

**Comment by benjamin-rose** [comment]
Unless by 'nested' it's referring to the ..include directive which I do use in a few cases. But I wouldn't call it deep nesting as I don't nest ..include directives inside other files called with ..include.

**Comment by TimKam** [comment]
Thanks for reporting this.
Generally, `sphinx-pretty-searchresults` also works with includes. To help me find the root of the problem, could you provide the following information:
* Can you run the Sphinx text build (`make text`) and check if the issue occurs there as well?
* A minimal example project that has the problem (or a link to your docs, if they are Open Source)

**Comment by benjamin-rose** [comment]
The issue doesn't occur with 'make text'. 

I have an example project for you. It seems to be related to using a custom template since I pared the project down to just a makefile, a table of contents, and a template file that overrides the basic layout.html. The override doesn't even do anything, just calls super, but it's possible I'm just doing something dumb. I was intending to use it to insert a custom CSS file, but took that out in trying to pare down the project. It looks like this may be an issue with template inheritance:

https://github.com/rtfd/readthedocs.org/issues/152

What's the best way to share this project with you? It's not currently online.

**Comment by benjamin-rose** [comment]
Ah, yes. Removing the layout.html override also fixes the problem. There are other ways to provide custom CSS files, as well. So I do have a good workaround.

**Comment by TimKam** [comment]
For the sake of completeness, it would be great if you could push the minimal example project that allows reproducing the bug to a newly created GitHub repo and post a link to it here.

**Comment by benjamin-rose** [comment]
Here you go:

https://github.com/benjamin-rose/sphinx-recursion-error

**Comment by TimKam** [comment]
Thanks, this is an actual bug. The extension can't handle custom template paths. I'll investigate some details and provide a fix.
