### ISSUE TITLE
Documents injected with include directive should be searched in context

### ISSUE THREAD

**Issue by benjamin-rose** [TimKam/sphinx-pretty-searchresults#19]
I think this is more of a suggestion than a bug. I have a number of files that are merely snippets of text that are injected into other documents using the ..include:: directive. When I do a search with sphinx-pretty-searchresults, these "snippet" documents are searched and presented as separate search results, even though they have little meaning on their own and don't even have titles to display. It would be better for my use case to present as a search result the final document they will be injected into. I've pasted an example of search results where this occurs in my project. Can this somehow be accommodated?

![image](https://user-images.githubusercontent.com/22225419/29691957-ca557248-88ea-11e7-8ac8-8fae6cf3ac39.png)

**Comment by TimKam** [comment]
This is a Sphinx configuration issue and not a bug.
By default, Sphinx builds all `.rst` files (or whatever file ending you specify) in your source directory.
Hence, it also builds files that are required by `.. include ::` statements, even if these files are not referenced in a ToC tree.
These files are consequently considered when creating the search index and included in the search results.
If you don't want Sphinx to build such files, use the ``exclude_patterns`` configuration option: http://www.sphinx-doc.org/en/stable/config.html#confval-exclude_patterns.
To not lose track, it makes sense to manage these files in a dedicated `include` folder.
