### ISSUE TITLE
Horizontal line markup isn't removed

### ISSUE THREAD

**Issue by Holger-S** [TimKam/sphinx-pretty-searchresults#21]
Horizontal lines represented in *.rst files by at least 4 hyphen characters like
``----``
at the beginning of a line aren't removed in the *.txt files.

Instead, 71 ``=`` chars are left in the txt files at the beginning of that line like this:
``======================================================================``

I'm using sphinx 1.6.3 and the latest sphinx-pretty-searchresults build.

**Comment by TimKam** [comment]
I cannot reproduce this issue. There's even a passing test for this type of markup. Slightly changing the test example doesn't lead to any problems. Could you provide an example `.rst` file?

**Comment by Holger-S** [comment]
Hi, of course.

``.rst`` file:
https://gist.github.com/Holger-S/feeaf822b7821be437876d7bdbe62a30

resulting ``.txt`` file:
https://gist.github.com/Holger-S/3b73391c8f2e0d18f44ac8f938437b17

**Comment by TimKam** [comment]
Thanks, now I can reproduce the issue. I will fix it asap.
