### ISSUE TITLE
Markdown files get saved with an RST file extension during processing

### ISSUE THREAD

**Issue by AndyMDoyle** [TimKam/sphinx-pretty-searchresults#23]
When searching, the search snippet is not displayed if the search result is for a Markdown file.

I spotted this after uploading the site to an AWS S3 bucket for testing, and noticed that the snippet underneath a markdown page displayed the HTML markup of the S3 404 page.

On disk we have the following:

`_raw_sources\getting-started.md.txt`

But sphinx-pretty-searchresults processes this and we end up with:

`_sources\getting-started.rst.txt`

For some reason the original extension is being changed to ".rst"

If I rename getting-started.rst.txt back to getting-started.md.txt in the _sources folder, the snippet is correctly displayed.

**Comment by TimKam** [comment]
Thanks for reporting! I have an idea where in the code the problem occurs and will work on a fix as soon as I find time.
