### ISSUE TITLE
Directory HTML builder support

### ISSUE THREAD

**Issue by Princesseuh** [TimKam/sphinx-pretty-searchresults#25]
Hi!

I recently switched my documentation to the [directory HTML builder](http://www.sphinx-doc.org/en/master/builders.html#sphinx.builders.html.DirectoryHTMLBuilder) for prettier URLs but quickly noticed that it broke this extension [since it's not enabled for other builders](https://github.com/TimKam/sphinx-pretty-searchresults/blob/master/sphinxprettysearchresults/__init__.py#L61)

Simply changing the lines locally to also support the dirhtml builder fixed the issue seemingly without problems, though I haven't tested all features (sourcelinks etc)

**Comment by TimKam** [comment]
Thanks for reporting. It shouldn't be too hard to support `dirhtml`. Could create a pull request with your local changes?
