### ISSUE TITLE
sphinx-pretty-searchresults does not respect sphinx-build -c paramter

### ISSUE THREAD

**Issue by alexsuter** [TimKam/sphinx-pretty-searchresults#29]
i get a build error when i use -c parameter in my sphinx-build. i want to locate the conf.py somewhere else. but sphinx-pretty-searchresults  needs the conf.py in the source directory.

```
Application error:
config directory doesn't contain a conf.py file (/ivy-core/doc/source)
make: Leaving directory '/doc-build'
```

**Comment by TimKam** [comment]
Thanks for reporting. Note that in the latest version of Sphinx, the search result issue is fixed. So you shouldn't need this extension anymore.

**Comment by alexsuter** [comment]
Issue closed, because not needed.

**Comment by jayaddison** [comment]
> Thanks for reporting. Note that in the latest version of Sphinx, the search result issue is fixed. So you shouldn't need this extension anymore.

Hi @TimKam - would you mind adding a message to the top of the README to let people know that this extension is no longer required with Sphinx version 2.0.0 and later?
