### ISSUE TITLE
Not all types of node are cleaned

### ISSUE THREAD

**Issue by pybride** [TimKam/sphinx-pretty-searchresults#5]
Several node types are missing, like **list_item** or **term**.

I tried to add theses in the script, goes well for list_item, but not term.

Also, the generated table of content isn't cleaned

**Comment by TimKam** [comment]
Thanks for the report, I'll fix it asap.

**Comment by TimKam** [comment]
I fixed the issue for the specific node types you mentioned and created a follow-up ticket: https://github.com/TimKam/sphinx-pretty-searchresults/issues/6.

**Comment by pybride** [comment]
Thanks for the quick fix.
